import { Inter } from "next/font/google";
import { MathJaxContext } from "better-react-mathjax";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata = {
  title: "mathjax",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className={`${inter.variable} antialiased`}>
        <MathJaxContext>{children}</MathJaxContext>
      </body>
    </html>
  );
}
